[theme]
base = "light"
primaryColor = "#007AFF"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#484848"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false